### ISSUE TITLE
arm container image

### ISSUE THREAD

**Issue by mkohns** [cedalo/management-center#33]
Hi, 

linux/arm container images for version 2.2.3 and 2.2.2 are not available on hub.docker.com.
Is this a bug or are you planning to provide future versions only for linux/amd64?

**Comment by cleancoderocker** [comment]
Hi,

now they are there 😊 

- [2.2.2](https://hub.docker.com/layers/cedalo/management-center/2.2.2-arm32v7/images/sha256-53ea86c8454d94edf516c289e90f1a2d79a66de205a77d79a0d4d51b3247b7f2?context=repo)
- [2.2.3](https://hub.docker.com/layers/cedalo/management-center/2.2.3-arm32v7/images/sha256-8bf7a02c730776a3a46fd4f361c24e5b4db34b9127bc9fbcb3112d81ca22a118?context=repo)
