### ISSUE TITLE
Cannot upgrade from 2.2.3 to >= 2.3

### ISSUE THREAD

**Issue by mereshow** [cedalo/management-center#39]
I have a container with a solo installation of management-center 2.2.3 (open source version, no license) running without issues. I have the broker connection parameter setup in environment variables.
I tried to upgrade to 2.3 (and 2.3.3 also) but the frontend shows a dialog to setup the broker connection. The same values as the ones I was using give the following error (shown in the snackbar), and I cannot connect:

`Error creating connection "_My Mosquitto broker_". Reason: BaseMosquittoProxyClient: Timeout`

If I revert back to 2.2.3 everything works properly.

I tried a new solo installation, with new volumes for the config, but I get the same problem. The container logs show (I think there is a regression with [issue-768543431](https://github.com/cedalo/management-center/issues/17#issue-768543431)):
```
Starting Management Center for Eclipse Mosquitto
No license key found or provided.
Fri, 11 Mar 2022 08:14:33 GMT express-session deprecated undefined resave option; provide resave option at start.js:195:24
Fri, 11 Mar 2022 08:14:33 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at start.js:195:24
Started Mosquitto proxy at http://localhost:8088
"CEDALO_MC_PLUGIN_DIR" is not set. Skipping loading of plugins
Mosquitto proxy server started on port 8088
No license key found or provided.
No license key found or provided.
No license key found or provided.
...
```

If I delete the dialog (using the Chrome's Developer tools), I can see that the frontend shows the following message:

```System status information not accessible
We couldn't retrieve the system status information. 
Please make sure that the user "" has the rights to read the "$SYS" topic on the selected broker.
```

I cleared all the cookies, cache, etc., but nothing works (but revert to 2.2.3).

In Chrome, the console shows these errors:

![image](https://user-images.githubusercontent.com/4802386/157834835-aad934cd-1fa1-457d-8662-21f7322cb392.png)

Is there some new configuration I am missing for versions >= 2.3?
I checked all the documentation but found nothing.

**Comment by cleancoderocker** [comment]
This should be fixed now in the new version 2.3.4.

**Comment by cleancoderocker** [comment]
(will update the 2.3 image later)

**Comment by mereshow** [comment]
The update works now! Thank you!
