### ISSUE TITLE
Too many debug messages that even show user credentials

### ISSUE THREAD

**Issue by mereshow** [cedalo/management-center#40]
There are way too many (hundreds per second) console debug messages of whole objects that should only be seen in development. This slows the app down.

Some of the debug shows the user credentials as plain text!

![image](https://user-images.githubusercontent.com/4802386/158176090-e7e761a2-8c29-4a42-b683-4e472dc0f240.png)

**Comment by cleancoderocker** [comment]
I've just build the 2.3.4 image again. Console output should be removed now.

**Comment by cleancoderocker** [comment]
The "Sending empty request" is just a ping/pong between the client and the server (you should see a similar output on the backend). We will remove that in the future.
