### ISSUE TITLE
No Docker image for ARM64

### ISSUE THREAD

**Issue by Lucy2003** [cedalo/management-center#48]
Hi,

I'm trying to install it on my RasPi 3 whose system is Ubuntu Server 64bit.
When I tried to start it,it reads:
```
Pulling management-center (cedalo/management-center:2)...
2: Pulling from cedalo/management-center
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

Could you please help me?Thanks.

**Comment by shantanoo-desai** [comment]
@Lucy2003 maybe use `docker buildx` kit to cross-compile the Docker image for armv8. See [Docs for buildx by Docker](https://www.docker.com/blog/multi-platform-docker-builds/)

**Comment by scargill** [comment]
I've just tried to add the docker version on RPi5 - using BOOKWORK Pi OS 64 bit -  there is no image for arm8.   HELP....
